schema = 3

[mod]
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20230301143203-a9d515a09cc2"
    hash = "sha256-UCENzt1c1tFgsAzK2TNq5s2g0tQMQ5PxFaQKe8hTL/A="
  [mod."github.com/bahlo/generic-list-go"]
    version = "v0.2.0"
    hash = "sha256-BIzqwG61hnMDknZOn/5+VX09yemzFzMjhPF48XoALto="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/buger/jsonparser"]
    version = "v1.1.1"
    hash = "sha256-T6dXT6Vzpm8gvQYi+c2LZkV+8ZOp0ZXBX7+e1mlliZE="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/analysis"]
    version = "v0.23.0"
    hash = "sha256-IhmB56h2BsbCvKEn7bm7fWw0pOkMZMXglZrC5iKlVjQ="
  [mod."github.com/go-openapi/errors"]
    version = "v0.22.0"
    hash = "sha256-OjXbNmPOlTcpfuHd7OS1cm5GTQLRNUJ8wxbsaef+M1o="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.21.0"
    hash = "sha256-bB8XTzo4hzXemi8Ey3tIXia3mfn38bvwIzKYLJYC650="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.21.0"
    hash = "sha256-lkFb/kP0qt8L1jsLYLt+jXTY6jSk5SYJbfgAKKVlQYQ="
  [mod."github.com/go-openapi/loads"]
    version = "v0.22.0"
    hash = "sha256-LSVRctUn05h6El+/MKQ9ZhnE8sZqjJJFTpt4Umm7jGI="
  [mod."github.com/go-openapi/runtime"]
    version = "v0.28.0"
    hash = "sha256-kPIwKPrEr6YuJXWZvJxoXXFXtj3g3ssyoQnTrGzxBxM="
  [mod."github.com/go-openapi/spec"]
    version = "v0.21.0"
    hash = "sha256-TNaIDffo6lw2v9n7mpM+gPgJJOK88PD6sp/LPNU7Fx8="
  [mod."github.com/go-openapi/strfmt"]
    version = "v0.23.0"
    hash = "sha256-OhuDzohJKR49ESRSD7n4YdeKAvLWwXMgKE/4FMBb++c="
  [mod."github.com/go-openapi/swag"]
    version = "v0.23.0"
    hash = "sha256-D5CzsSQ3SYJLwXT6BDahnG66LI8du59Dy1mY4KutA7A="
  [mod."github.com/go-openapi/validate"]
    version = "v0.24.0"
    hash = "sha256-dISwTJag5g8FXXp7CDk4KR3t7FJUn7iM2hATBlKMcJw="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grafana/grafana-openapi-client-go"]
    version = "v0.0.0-20250108132429-8d7e1f158f65"
    hash = "sha256-WTmSUxd2hy9cZYPeVvza34nl1PwytY1ckp5AdCm2oXs="
  [mod."github.com/grafana/incident-go"]
    version = "v0.0.0-20250211094540-dc6a98fdae43"
    hash = "sha256-iEz5uH+88mWmKHlBo6KRF1bYqvDZDXB8zUJ/qsoROs4="
  [mod."github.com/grafana/regexp"]
    version = "v0.0.0-20240518133315-a468a5bfb3bc"
    hash = "sha256-bNmTHk8HpaEMthizI+vceMp9R9CQAgmeklsHyveDM3Q="
  [mod."github.com/invopop/jsonschema"]
    version = "v0.13.0"
    hash = "sha256-Fe4DQDJQxy5i8cgJY6dFbraTnfG/C2D3cB1Q5p2QxVc="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/jpillora/backoff"]
    version = "v1.0.0"
    hash = "sha256-uxHg68NN8hrwPCrPfLYYprZHf7dMyEoPoF46JFx0IHU="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mark3labs/mcp-go"]
    version = "v0.15.0"
    hash = "sha256-Gbj+mJdtv+6GqjwzHG24adM91dyG59YQlN+Xtk8kQmY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/mwitkow/go-conntrack"]
    version = "v0.0.0-20190716064945-2f068394615f"
    hash = "sha256-h6tgygomf/oVKMa2MO8sPLUD3CxK81z5q/roKYKvsno="
  [mod."github.com/oklog/ulid"]
    version = "v1.3.1"
    hash = "sha256-LNn883rYNiaoY9sGEPIzlMRx5UwGThdYTjXqfzeGc9k="
  [mod."github.com/opentracing/opentracing-go"]
    version = "v1.2.0"
    hash = "sha256-kKTKFGXOsCF6QdVzI++GgaRzv2W+kWq5uDXOJChvLxM="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.21.0"
    hash = "sha256-ZK2NxVg1GSAa3ZYwpgc53KQcyjgdqYUpPCjvDxLkzc4="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.62.0"
    hash = "sha256-UFccvzMJaBrUpnqVgZgohRcgk5SKMi/UJnXNtazCnx8="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/prometheus/prometheus"]
    version = "v0.302.1"
    hash = "sha256-Mn2CEXVz8CuXN48SwRB2NH9yfJWthy4KSfxxakecKRI="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/wk8/go-ordered-map/v2"]
    version = "v2.1.8"
    hash = "sha256-v7/5+7lAypZfgClXgWxhxtA1skQq9o+1yrI+V0o1j2o="
  [mod."github.com/yosida95/uritemplate/v3"]
    version = "v3.0.2"
    hash = "sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.14.0"
    hash = "sha256-nG9fZIdSVExXLgJSrdp3ZU+X2lHhIyJRcvIEMRtnAWA="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.34.0"
    hash = "sha256-hnuuTSxaf9yMO/23xWdcTGNzvnnJiqUiL4nzYwUV5bc="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.34.0"
    hash = "sha256-JklGKJiMf1fpsE9pmnuLUq26g6wVp173v4GWJ7Xp5s4="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.34.0"
    hash = "sha256-u11KJ4WTDtcb0tVv7d/HOdhq8Ea+c1QPBO8MbsCQu9Q="
  [mod."golang.org/x/net"]
    version = "v0.34.0"
    hash = "sha256-AZOLY4MUNxxDw5ZQtO9dmY/YRo1gFW87YvpX/eLTy4Q="
  [mod."golang.org/x/oauth2"]
    version = "v0.25.0"
    hash = "sha256-MpFrvO9Z54mFG1Zi6V1GIEJY8Paq9SCWbgvuy+J55+Y="
  [mod."golang.org/x/sync"]
    version = "v0.10.0"
    hash = "sha256-HWruKClrdoBKVdxKCyoazxeQV4dIYLdkHekQvx275/o="
  [mod."golang.org/x/sys"]
    version = "v0.29.0"
    hash = "sha256-qfsodJQ1H1CBI8yQWOvsXJgY5qHmiuw566HrrIseYHI="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.4"
    hash = "sha256-+5wKklNoydwfYpx4BVhKjLNhqlisN9ddxhyGb8uP6a8="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
